### PR TITLE
attacker: Simplify timeout configuration

### LINKED ISSUE #396: io timeout in attack_test.go:122
#### Version and Runtime

building 12.3.0 at Arch Linux

#### Expected Behaviour

Tests passed when I do `go test ./...`

#### Actual Behaviour

Tests fail:
```
# github.com/tsenart/vegeta/lib/lttb.test
loadinternal: cannot find runtime/cgo
ok  	github.com/tsenart/vegeta	0.004s
?   	github.com/tsenart/vegeta/internal/cmd/echosrv	[no test files]
?   	github.com/tsenart/vegeta/internal/cmd/jsonschema	[no test files]
ok  	github.com/tsenart/vegeta/internal/resolver	0.004s
--- FAIL: TestTimeout (0.01s)
    attack_test.go:122: want: 'net/http: timeout awaiting response headers' in 'Get http://127.0.0.1:34471: dial tcp 0.0.0.0:0->127.0.0.1:34471: i/o timeout'
FAIL
FAIL	github.com/tsenart/vegeta/lib	1.065s
ok  	github.com/tsenart/vegeta/lib/lttb	3.056s
ok  	github.com/tsenart/vegeta/lib/plot	0.918s
```

#### Steps to Reproduce

Install Arch Linux, try to build `vegeta` package from the official repository.

### PR DESCRIPTION
**Pull request by tsenart**
This commit simplifies the timeout configuration internally to make use
of the `http.Client.Timeout` field which didn't exist when this code was
originally written.

It also fixes #396: a test flake of `TestTimeout`.

### CODE REVIEW

File: lib/attack_test.go [hunk 1]
```diff
@@ -117,7 +117,7 @@ func TestTimeout(t *testing.T) {
 	atk := NewAttacker(Timeout(10 * time.Millisecond))
 	tr := NewStaticTargeter(Target{Method: "GET", URL: server.URL})
 	res := atk.hit(tr, "")
-	want := "net/http: timeout awaiting response headers"
+	want := "Client.Timeout exceeded while awaiting headers"
 	if got := res.Error; !strings.HasSuffix(got, want) {
```
Comment (tsenart) [inline lib/attack_test.go]:
```suggestion
	if got := res.Error; !strings.Contains(got, want) {
```
