### PR TITLE
results: Faster JSON encoding and decoding

### LINKED ISSUE #505: HTTP headers in results produce invalid JSON
#### Version and Runtime

```
Version: 12.8.1
Commit: 19b7458
Runtime: go1.14 darwin/amd64
Date: 2020-03-18T23:14:26Z
```

#### Expected Behaviour

I expected to be able to use `jq` to process JSON formatted vegeta results:
`echo 'GET http://httpbin.org/get' | vegeta attack -rate=1 -duration=1s | vegeta encode" | jq`
```
{
  "attack": "",
  "seq": 0,
  "code": 200,
  "timestamp": "2020-03-23T22:55:59.3708787Z",
  "latency": 293490600,
  "bytes_out": 0,
  "bytes_in": 271,
  "error": "",
  "body": "..."
}
```

#### Actual Behaviour

```
echo "GET http://httpbin.org/get" | vegeta attack -rate=1 -duration=1s | vegeta encode | jq  
parse error: Expected separator between values at line 1, column 655
```

#### Steps to Reproduce

1. `echo "GET http://httpbin.org/get" | vegeta attack -rate=1 -duration=1s | vegeta encode`

This produces output like
```
{"attack":"","seq":0,"code":200,"timestamp":"2020-03-23T17:58:33.347828102-05:00","latency":291316215,"bytes_out":0,"bytes_in":297,"error":"","body":"...","method":"GET","url":"http://httpbin.org/get","headers":[{"key":"Server","value":"gunicorn/19.9.0"}{"key":"Access-Control-Allow-Origin","value":"*"}{"key":"Access-Control-Allow-Credentials","value":"true"}{"key":"Date","value":"Mon, 23 Mar 2020 22:58:33 GMT"}{"key":"Content-Type","value":"application/json"}{"key":"Content-Length","value":"297"}{"key":"Connection","value":"keep-alive"}]}
```

The objects in the `headers` array are missing commas between them.

### PR DESCRIPTION
**Pull request by tsenart**
This commit improves the performance of JSON encoding and decoding of
`Results`. Additionally, it fixes a regression introduced in #474 that
didn't produce valid JSON for HTTP headers. A test is added that
validates the JSON encoding matches the one produced by the
`encoding/json`.

Screenshot from 2020-03-24 15-07-36

Fixes #505

### CODE REVIEW

File: lib/results_json.go [hunk 1]
```diff
@@ -0,0 +1,268 @@
...
+	sh := (*reflect.StringHeader)(unsafe.Pointer(&s))
+	bh := reflect.SliceHeader{
+		Data: sh.Data,
+		Len:  sh.Len,
+		Cap:  sh.Len,
+	}
+	return *(*[]byte)(unsafe.Pointer(&bh))
+}
+
+func b2s(z []byte) string {
```
Comment (golangcibot) [inline lib/results_json.go]: func `b2s` is unused (from `unused`)

File: lib/results_test.go [hunk 2]
```diff
@@ -141,19 +157,25 @@ func BenchmarkResultEncodings(b *testing.B) {
...
 		b.Run(tc.encoding+"-encode", func(b *testing.B) {
 			for i := 0; i < b.N; i++ {
 				enc.Encode(&results[i%len(results)])
 			}
 		})
 
+		var buf bytes.Buffer
+		enc = tc.enc(&buf)
+		for _, r := range results {
+			enc.Encode(&r)
```
Comment (golangcibot) [inline lib/results_test.go]: Error return value of `enc.Encode` is not checked (from `errcheck`)

File: lib/results_test.go [hunk 3]
```diff
@@ -141,19 +157,25 @@ func BenchmarkResultEncodings(b *testing.B) {
...
+		}
+
 		dec := tc.dec(&buf)
 		b.Run(tc.encoding+"-decode", func(b *testing.B) {
+			var r Result
 			for i := 0; i < b.N; i++ {
-				dec.Decode(&results[i%len(results)])
+				dec.Decode(&r)
```
Comment (golangcibot) [inline lib/results_test.go]: Error return value of `dec.Decode` is not checked (from `errcheck`)
